### ISSUE TITLE
docker-novolume-plugin should be socket activated

### ISSUE THREAD

**Issue by rhatdan** [projectatomic/docker-novolume-plugin#4]
This way if it dies or the next authorization will create it again.

docker-novolume-plugin might suffer the same problems that docker does as far as writing to stdout/stderr if journald dies.  
It should be doing all of its output to syslog.

We want to make sure that docker rejects everything if the auth plugins die.

**Comment by runcom** [comment]
@rhatdan docker will eventually reject everything if one of the plugins dies because it will time out trying  to  reach  the plugin 

I might have to understand better what's actually happening if plugins die after being lazy initialized

Thanks for opening this reminder

**Comment by runcom** [comment]
Ack to logs to syslog though

**Comment by runcom** [comment]
already done upstream

**Comment by rhatdan** [comment]
Awesome.
