### ISSUE TITLE
This should have a config file.

### ISSUE THREAD

**Issue by rhatdan** [projectatomic/docker-novolume-plugin#6]
Once we get authorization in, I would want to be able to say that dwalsh is allowed to create volumes on the host.

**Comment by runcom** [comment]
@rhatdan can we leave this opened and address this in docker 1.11 release cycle? just so we don't iterate over again if things upstream change

**Comment by rhatdan** [comment]
Sure.  Just mention this in README, that you want to add a config file to allow users/groups to override the default.

**Comment by runcom** [comment]
https://github.com/projectatomic/docker-novolume-plugin#future
