### ISSUE TITLE
Needs man page

### ISSUE THREAD

**Issue by rhatdan** [projectatomic/docker-novolume-plugin#7]

**Comment by runcom** [comment]
on it

**Comment by runcom** [comment]
there's still a Task in the trello card I've to do for man page

**Comment by rhatdan** [comment]
Can't be 1.0 without some documentation.  Probably need some "How to Test" added to the ReadMe so QE knows what to look for.

**Comment by runcom** [comment]
make sense will fix

**Comment by runcom** [comment]
Fixed in master
